language: ruby
cache: bundler
env:
  - CPLUS_INCLUDE_PATH=/usr/include:/usr/include/atlas C_INCLUDE_PATH=/usr/include:/usr/include/atlas
rvm:
  - "2.1.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev libatlas-base-dev
script: bundle exec rake
notifications:
  irc: "chat.freenode.net#sciruby"
